<script>
    import UpgradeTabs from "@/components/UpgradeTabs.svelte";
    import HeadingLink from "@/components/HeadingLink.svelte";
    import Toc from "@/components/Toc.svelte";
</script>

<p class="txt-hint txt-sm">
    For the Go version please refer to <a href="/v023upgrade/go/">/v023upgrade/go</a>.
</p>

<Toc headingSelector="h1,h2,h3" />

<HeadingLink title="Upgrade overview" />

<div class="alert alert-warning m-b-xs">
    <div class="content">
        <p>
            Please note that you don't have to upgrade to v0.23.0 if you are not planning further developing
            your existing app or are satisfied with the v0.22.x features set. There are no critical issues
            with PocketBase v0.22.x and in the case of reported bugs and security vulnerabilities, the fixes
            will be backported for at least until Q1 of 2025 (<em>if not longer</em>).
        </p>
        <p>
            If you don't plan upgrading just make sure to pin the SDKs version to their latest PocketBase
            v0.22.x compatible:
        </p>
        <ul>
            <li>JS SDK: <code>{`<0.22.0`}</code></li>
            <li>Dart SDK: <code>{`<0.19.0`}</code></li>
        </ul>
    </div>
</div>

<p class="inline-flex">
    <i class="ri-alert-fill txt-warning"></i>
    <strong>
        Before upgrading make sure to backup your current <code>pb_data</code> directory somewhere safe.
    </strong>
</p>

<p>
    PocketBase v0.23+ comes with many changes and requires applying manual migration steps for the
    <code>pb_hooks</code> and <code>pb_migrations</code>.
    <br />
    Existing data in <code>pb_data/data.db</code> will be automatically upgraded once the PocketBase v0.23.0
    executable is started.
    <br />
    But there is no easy and automated code upgrade solution so be prepared because it might take you some time
    - from 1h to entire weekend!
</p>

<p>Suggested upgrade path:</p>
<ol start="0">
    <li>
        Download a backup of your production <code>pb_data</code> so that you can adjust your code and test the
        upgrade locally.
    </li>
    <li>
        Ensure that you are already using PocketBase v0.22.x (you can find the version number in the
        bottom-right corner in the UI). If you are using an older version, please upgrade first to
        <a
            href="https://github.com/pocketbase/pocketbase/releases/tag/v0.22.27"
            target="_blank"
            rel="noopener noreferrer"
        >
            PocketBase v0.22.x
        </a>
        (there are no major breaking changes in the recent v0.22.x releases so it should be enough to download
        the specific executable and run it against your <code>pb_data</code>).
    </li>
    <li>
        If you are using the SDKs, apply the necessary changes to your client-side code by following:
        <ul>
            <li>
                <a
                    href="{import.meta.env.PB_JS_SDK_URL}/blob/master/CHANGELOG.md"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    JS SDK v0.22+ CHANGELOG
                </a>
            </li>
            <li>
                <a
                    href="{import.meta.env.PB_DART_SDK_URL}/blob/master/CHANGELOG.md"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    DART SDK v0.19+ CHANGELOG
                </a>
            </li>
        </ul>
    </li>
    <li>
        If your existing <code>pb_migrations</code> files are all autogenerated, you may find it easier to
        upgrade by deleting all of them and run with the PocketBase v0.23.0 executable
        <code>./pocketbase migrate collections</code>
        which will create a full snapshot of your latest collections configuration.
        <br />
        <em>
            Optionally, after that you can also run <code>./pocketbase migrate history-sync</code> to remove the
            deleted migrations from the applied migrations history.
        </em>
    </li>
    <li>
        Apply the necessary <code>pb_hooks</code> code changes based on the notes listed below in this document.
    </li>
    <li>
        Start PocketBase v0.23.0 as usual and test your local changes (<strong
            >including a test against no existing pb_data</strong
        >).
    </li>
    <li>
        If everything is working fine, create another more recent production backup for just in case.
        <br />
        After that you can deploy your PocketBase v0.23.0 executable, together with the upgraded client-side code,
        <code>pb_hooks</code>
        and <code>pb_migrations</code> to your production server.
    </li>
</ol>

<div class="alert">
    <div class="content">
        <p>The below listed changes doesn't cover everything but it should be a good starting point.</p>
        <p>
            If you need help with the "translation" of your old code to the new APIs, feel free to open a
            <a href={import.meta.env.PB_DISCUSSIONS_URL} target="_blank" rel="noopener noreferrer">
                Q&A discussion
            </a>
            with the specific code sample and I'll try to assist you.
        </p>
    </div>
</div>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Initialisms case normalization" />
<p>
    For consistency with the Go standard library and to silent commonly used linters the following initilisms
    case normalization was applied for all exported bindings:
</p>
<table class="table-compact table-border" style="min-width: auto;">
    <thead>
        <tr>
            <th>Old</th>
            <th>New</th>
        </tr>
    </thead>
    <tbody>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Json<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>JSON</strong><span class="txt-hint">%</span></td>
        </tr>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Ip<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>IP</strong><span class="txt-hint">%</span></td>
        </tr>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Url<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>URL</strong><span class="txt-hint">%</span></td>
        </tr>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Smtp<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>SMTP</strong><span class="txt-hint">%</span></td>
        </tr>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Tls<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>TLS</strong><span class="txt-hint">%</span></td>
        </tr>
        <tr valign="top">
            <td><span class="txt-hint">%</span>Jwt<span class="txt-hint">%</span></td>
            <td><span class="txt-hint">%</span><strong>JWT</strong><span class="txt-hint">%</span></td>
        </tr>
    </tbody>
</table>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="App changes" />
<div class="alert">
    <div class="content">
        <p>
            The <code>Dao</code> abstraction has been removed and most of the old <code>Dao</code>
            methods are now part of the <code>$app</code> instance.
        </p>
        <p>
            The app settings related to the OAuth2 and email templates are moved in the collection options to
            allow more granular customizations.
        </p>
        <p>
            For more details about all new app fields and methods, please refer to the
            <code>$app.*</code> docs in the
            <a href="/jsvm/modules/_app.html" target="_blank">JSVM reference</a>.
        </p>
    </div>
</div>

<UpgradeTabs before={`$app.cache()`} after={`$app.store()`} />

<UpgradeTabs before={`$app.refreshSettings()`} after={`$app.reloadSettings()`} />

<HeadingLink
    tag="h6"
    title={`Admin DB methods (admins are now system "_superusers" auth collection records)`}
/>

<UpgradeTabs before={`$app.dao().adminQuery()`} after={`$app.recordQuery("_superusers")`} />

<UpgradeTabs before={`$app.dao().findAdminById(id)`} after={`$app.findRecordById("_superusers", id)`} />

<UpgradeTabs
    before={`$app.dao().findAdminByEmail(email)`}
    after={`$app.findAuthRecordByEmail("_superusers", email)`}
/>

<UpgradeTabs
    before={`$app.dao().findAdminByToken(token, baseTokenKey)`}
    after={`
        // tokenType could be:
        // - auth
        // - file
        // - verification
        // - passwordReset
        // - emailChange
        $app.findAuthRecordByToken(token, [tokenType])
    `}
/>

<UpgradeTabs before={`$app.dao().totalAdmins()`} after={`$app.countRecords("_superusers", [exprs...])`} />

<UpgradeTabs before={`$app.dao().deleteAdmin(admin)`} after={`$app.delete(admin)`} />

<UpgradeTabs before={`$app.dao().saveAdmin(admin)`} after={`$app.save(admin)`} />

<HeadingLink tag="h6" title={`Record DB methods`} />

<UpgradeTabs
    before={`$app.dao().recordQuery(collectionModelOrIdentifier)`}
    after={`$app.recordQuery(collectionModelOrIdentifier)`}
/>

<UpgradeTabs
    before={`$app.dao().findRecordById(collectionNameOrId, recordId, [optFilters...])`}
    after={`$app.findRecordById(collectionModelOrIdentifier, recordId, [optFilters...])`}
/>

<UpgradeTabs
    before={`$app.dao().findRecordsByIds(collectionNameOrId, recordIds, [optFilters...])`}
    after={`$app.findRecordsByIds(collectionModelOrIdentifier, recordIds, [optFilters...])`}
/>

<UpgradeTabs
    before={`$app.dao().findRecordsByExpr(collectionNameOrId, [exprs...])`}
    after={`$app.findAllRecords(collectionModelOrIdentifier, [exprs...])`}
/>

<UpgradeTabs
    before={`$app.dao().findFirstRecordByData(collectionNameOrId, key, value)`}
    after={`$app.findFirstRecordByData(collectionModelOrIdentifier, key, value)`}
/>

<UpgradeTabs
    before={`$app.dao().findRecordsByFilter(collectionNameOrId, filter, sort, limit, offset, [params])`}
    after={`app.findRecordsByFilter(collectionModelOrIdentifier, filter, sort, limit, offset, [params])`}
/>

<UpgradeTabs before={`N/A`} after={`$app.countRecords(collectionModelOrIdentifier, [exprs...])`} />

<UpgradeTabs
    before={`$app.dao().findAuthRecordByToken(token, baseTokenKey)`}
    after={`
        // tokenType could be:
        // - auth
        // - file
        // - verification
        // - passwordReset
        // - emailChange
        $app.findAuthRecordByToken(token, [tokenType])
    `}
/>

<UpgradeTabs
    before={`$app.dao().findAuthRecordByEmail(collectionNameOrId, email)`}
    after={`$app.findAuthRecordByEmail(collectionModelOrIdentifier, email)`}
/>

<UpgradeTabs
    before={`$app.dao().findAuthRecordByUsername(collectionNameOrId, username)`}
    after={`
        // The "username" field is no longer required and has no special meaning.
        $app.findFirstRecordByData(collectionModelOrIdentifier, "username", username)
    `}
/>

<UpgradeTabs
    before={`$app.dao().suggestUniqueAuthRecordUsername(collectionNameOrId, baseUsername, [excludeIds...])`}
    after={`
        // The "username" field is no longer required and has no special meaning. As a workaround you can use something like:
        function suggestUniqueAuthRecordUsername(
          collectionModelOrIdentifier,
          baseUsername,
        ) {
          let username = baseUsername
          for (i = 0; i < 10; i++) { // max 10 attempts
            try {
              let total = $app.countRecords(
                collectionModelOrIdentifier,
                $dbx.exp("LOWER([[username]])={:username}", {"username": username.toLowerCase()}),
              )
              if (total == 0) {
                break // already unique
              }
            } catch {}

            username = baseUsername + $security.randomStringWithAlphabet(3+i, "123456789")
          }

          return username
        }
    `}
/>

<UpgradeTabs
    before={`$app.dao().canAccessRecord(record, requestInfo, accessRule)`}
    after={`$app.canAccessRecord(record, requestInfo, accessRule)`}
/>

<UpgradeTabs
    before={`$app.dao().expandRecord(record, expands, optFetchFunc)`}
    after={`$app.expandRecord(record, expands, optFetchFunc)`}
/>

<UpgradeTabs
    before={`$app.dao().expandRecords(records, expands, optFetchFunc)`}
    after={`$app.expandRecords(records, expands, optFetchFunc)`}
/>

<UpgradeTabs before={`$app.dao().saveRecord(record)`} after={`$app.save(record)`} />

<UpgradeTabs before={`$app.dao().deleteRecord(record)`} after={`$app.delete(record)`} />

<HeadingLink tag="h6" title={`ExternalAuth DB methods (converted to "_externalAuths" collection records)`} />

<UpgradeTabs
    before={`$app.dao().findAllExternalAuthsByRecord(authRecord)`}
    after={`$app.findAllExternalAuthsByRecord(authRecord)`}
/>

<UpgradeTabs before={`N/A`} after={`$app.findAllExternalAuthsByCollection(collection)`} />

<UpgradeTabs
    before={`$app.dao().findFirstExternalAuthByExpr(expr)`}
    after={`$app.findFirstExternalAuthByExpr(expr)`}
/>

<UpgradeTabs
    before={`$app.dao().findExternalAuthByRecordAndProvider(authRecord)`}
    after={`
        $app.findFirstExternalAuthByExpr($dbx.hashExp({
            "collectionRef": authRecord.collection().id,
            "recordRef":     authRecord.id,
            "provider":      provider,
        }))
    `}
/>

<UpgradeTabs before={`$app.dao().deleteExternalAuth(model)`} after={`$app.delete(model)`} />

<UpgradeTabs before={`$app.dao().saveExternalAuth(model)`} after={`$app.save(model)`} />

<HeadingLink tag="h6" title={`Collection DB methods`} />

<UpgradeTabs before={`$app.dao().collectionQuery()`} after={`$app.collectionQuery()`} />

<UpgradeTabs
    before={`$app.dao().findCollectionsByType(collectionType)`}
    after={`$app.findAllCollections(collectionTypes...)`}
/>

<UpgradeTabs
    before={`$app.dao().findCollectionByNameOrId(nameOrId)`}
    after={`$app.findCollectionByNameOrId(nameOrId)`}
/>

<UpgradeTabs
    before={`$app.dao().isCollectionNameUnique(name, excludeIds...)`}
    after={`$app.isCollectionNameUnique(name, excludeIds...)`}
/>

<UpgradeTabs
    before={`$app.dao().findCollectionReferences(collection, excludeIds...)`}
    after={`$app.findCollectionReferences(collection, excludeIds...)`}
/>

<UpgradeTabs before={`$app.dao().deleteCollection(collection)`} after={`$app.delete(collection)`} />

<UpgradeTabs before={`$app.dao().saveCollection(collection)`} after={`$app.save(collection)`} />

<UpgradeTabs
    before={`$app.dao().importCollections(importedCollections, deleteMissing, afterSync)`}
    after={`$app.importCollections(importSliceOfMap, deleteMissing)`}
/>

<UpgradeTabs
    before={`N/A`}
    after={`$app.importCollectionsByMarshaledJSON(sliceOfMapsBytes, deleteMissing)`}
/>

<UpgradeTabs
    before={`$app.dao().syncRecordTableSchema(newCollection, oldCollection)`}
    after={`$app.syncRecordTableSchema(newCollection, oldCollection)`}
/>

<HeadingLink tag="h6" title={`Log DB methods`} />

<UpgradeTabs before={`$app.dao().logQuery()`} after={`$app.logQuery()`} />

<UpgradeTabs before={`$app.dao().findLogById(id)`} after={`$app.findLogById(id)`} />

<UpgradeTabs before={`$app.dao().logsStats(expr)`} after={`$app.logsStats(expr)`} />

<UpgradeTabs before={`$app.dao().deleteOldLogs(createdBefore)`} after={`$app.deleteOldLogs(createdBefore)`} />

<UpgradeTabs before={`$app.dao().saveLog(log)`} after={`$app.auxSave(log)`} />

<HeadingLink tag="h6" title={`Other DB methods`} />

<UpgradeTabs
    before={`$app.dao().saveSettings(newSettings, [optEncryptionKey])`}
    after={`$app.save(newSettings)`}
/>

<UpgradeTabs
    before={`
        const titles = ["title1", "title2", "title3"]

        const collection = $app.dao().findCollectionByNameOrId("articles")

        $app.dao().runInTransaction((txDao) => {
            // create new record for each title
            for (let title of titles) {
                const record = new Record(collection)

                record.set("title", title)

                txDao.saveRecord(record)
            }
        })
    `}
    after={`
        const titles = ["title1", "title2", "title3"]

        const collection = $app.findCollectionByNameOrId("articles")

        $app.runInTransaction((txApp) => {
            // create new record for each title
            for (let title of titles) {
                const record = new Record(collection)

                record.set("title", title)

                txApp.saveRecord(record)
            }
        })
    `}
/>

<UpgradeTabs before={`$app.dao().vacuum()`} after={`$app.vacuum() / $app.auxVacuum()`} />

<UpgradeTabs before={`$app.dao().hasTable(tableName)`} after={`$app.hasTable(tableName)`} />

<UpgradeTabs before={`$app.dao().tableColumns(tableName)`} after={`$app.tableColumns(tableName)`} />

<UpgradeTabs before={`$app.dao().tableInfo(tableName)`} after={`$app.tableInfo(tableName)`} />

<UpgradeTabs before={`$app.dao().tableIndexes(tableName)`} after={`$app.tableIndexes(tableName)`} />

<UpgradeTabs before={`$app.dao().deleteTable(tableName)`} after={`$app.deleteTable(tableName)`} />

<UpgradeTabs before={`$app.dao().deleteView(name)`} after={`$app.deleteView(name)`} />

<UpgradeTabs before={`$app.dao().saveView(name, selectQuery)`} after={`$app.saveView(name, selectQuery)`} />

<UpgradeTabs
    before={`$app.dao().createViewSchema(selectQuery)`}
    after={`$app.createViewFields(selectQuery)`}
/>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Record model changes" />
<p>
    The Record create/update operations are simplified and the <code>Dao</code> and
    <code>RecordUpsertForm</code> abstractions have been removed.
</p>
<p>
    <code>$app.save(record)</code> both validate and persist the record. Use
    <code>$app.saveNoValidate(record)</code> if you want to skip the validations.
</p>
<p>
    Files are treated as regular field value, so for uploading a new record file is enough to call
    <code>record.set("yourFileField", $filesystem.fileFromPath("/path/to/file1"))</code>.
</p>
<p>
    Additionally, the <code>record.set()</code> method now supports all field modifiers that are available
    with the Web APIs. For example:
    <code>record.set("total+", 10)</code> adds <code>10</code> to the existing <code>total</code> record field
    value. More information about the available modifiers you can find in the main documentation.
</p>

<HeadingLink tag="h6" title="RecordUpsertForm migration" />
<UpgradeTabs
    before={`
        const record = $app.dao().findRecordById("articles", "RECORD_ID")

        const form = new RecordUpsertForm($app, record)

        form.loadData({
            "title":  "Lorem ipsum",
            "active": true,
        })

        // upload file(s)
        const f1 = $filesystem.fileFromPath("/path/to/file1")
        const f2 = $filesystem.fileFromPath("/path/to/file2")
        form.addFiles("documents", f1, f2)

        // mark file(s) for deletion
        form.removeFiles("featuredImages", "demo_xzihx0w.png")

        form.submit()
    `}
    after={`
        const record = $app.findRecordById("articles", "RECORD_ID")

        // there is also record.load({ ... })
        record.set("title", "Lorem ipsum")
        record.set("active", true)

        // upload file(s)
        record.set("documents", [
            $filesystem.fileFromPath("/path/to/file1"),
            $filesystem.fileFromPath("/path/to/file2"),
        ])

        // mark file(s) for deletion
        record.set("featuredImages-", "demo_xzihx0w.png")

        $app.save(record)
    `}
/>

<HeadingLink tag="h6" title="Model changes" />
<UpgradeTabs before={`record.schemaData()`} after={`record.fieldsData()`} />
<UpgradeTabs before={`record.unknownData()`} after={`record.customData()`} />
<UpgradeTabs before={`record.withUnknownData(state)`} after={`record.withCustomData(state)`} />
<UpgradeTabs before={`record.originalCopy()`} after={`record.original()`} />
<UpgradeTabs before={`record.cleanCopy()`} after={`record.fresh()`} />
<UpgradeTabs before={`record.getTime(fieldName)`} after={`record.getDateTime(fieldName).Time()`} />

<HeadingLink tag="h6" title="$tokens.* merge" />
<UpgradeTabs before={`$tokens.recordAuthToken($app, record)`} after={`record.newAuthToken()`} />
<UpgradeTabs before={`$tokens.recordVerifyToken($app, record)`} after={`record.newVerificationToken()`} />
<UpgradeTabs
    before={`$tokens.recordResetPasswordToken($app, record)`}
    after={`record.newPasswordResetToken()`}
/>
<UpgradeTabs
    before={`$tokens.recordChangeEmailToken($app, record, newEmail)`}
    after={`record.newEmailChangeToken()`}
/>
<UpgradeTabs before={`$tokens.recordFileToken($app, record)`} after={`record.NewFileToken()`} />

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Collection model changes" />

<p>
    Added new dedicated collection type constructors:
    <code>{`new BaseCollection(name)`}</code>
    <code>{`new AuthCollection(name)`}</code>
    <code>{`new ViewCollection(name)`}</code>
</p>

<p>
    <code>Collection.schema</code> is now a regular array of fields and the model field is renamed to
    <code>Collection.fields</code>.
    <br />
    There are now also dedicated typed fields bindings equivalent to the Go ones as an alternative to
    <code>{`new Field({type: "...", ...})`}</code>:
</p>
<ul>
    <li>
        <a href="/jsvm/classes/NumberField.html" target="_blank"><code>{`new NumberField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/BoolField.html" target="_blank"><code>{`new BoolField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/TextField.html" target="_blank"><code>{`new TextField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/URLField.html" target="_blank"><code>{`new URLField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/EmailField.html" target="_blank"><code>{`new EmailField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/EditorField.html" target="_blank"><code>{`new EditorField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/DateField.html" target="_blank"><code>{`new DateField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/AutodateField.html" target="_blank">
            <code>{`new AutodateField({ ... })`}</code>
        </a>
    </li>
    <li>
        <a href="/jsvm/classes/JSONField.html" target="_blank"><code>{`new JSONField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/RelationField.html" target="_blank">
            <code>{`new RelationField({ ... })`}</code>
        </a>
    </li>
    <li>
        <a href="/jsvm/classes/SelectField.html" target="_blank"><code>{`new SelectField({ ... })`}</code></a>
    </li>
    <li>
        <a href="/jsvm/classes/FileField.html" target="_blank"><code>{`new FileField({ ... })`}</code></a>
    </li>
</ul>

<p>
    All previous dynamic <code>Collection.options.*</code> fields are flattened for consistency with the JSON Web
    APIs:
</p>
<UpgradeTabs before={`collection.options.query = "..."`} after={`collection.viewQuery = "..."`} />
<UpgradeTabs before={`collection.options.manageRule = "..."`} after={`collection.manageRule = "..."`} />
<UpgradeTabs
    before={`collection.options.onlyVerified = true`}
    after={`collection.authRule = "verified = true"`}
/>
<UpgradeTabs
    before={`collection.options.onlyVerified = true`}
    after={`collection.authRule = "verified = true"`}
/>
<UpgradeTabs
    before={`collection.options.allowOAuth2Auth = true`}
    after={`
        // note: providers can be set via collection.oauth2.providers
        collection.oauth2.enabled = true
    `}
/>
<UpgradeTabs
    before={`collection.options.allowUsernameAuth = true`}
    after={`
        collection.passwordAuth = {
            "enabled":      true,
            identityFields: ["username"],
        }
    `}
/>
<UpgradeTabs
    before={`collection.options.allowEmailAuth = true`}
    after={`
        collection.passwordAuth = {
            "enabled":      true,
            identityFields: ["email"],
        }
    `}
/>
<UpgradeTabs
    before={`
        collection.options.requireEmail = true
        collection.options.exceptEmailDomains = ["example.com"]
        collection.options.onlyEmailDomains = ["example.com"]
    `}
    after={`
        // you can adjust the system "email" field options in the same way as the regular Collection.fields, e.g.:
        collection.fields.getByName("email").require = true
        collection.fields.getByName("email").exceptDomains = ["example.com"]
        collection.fields.getByName("email").onlyDomains = ["example.com"]
    `}
/>
<UpgradeTabs
    before={`collection.options.minPasswordLength = 10`}
    after={`
        // you can adjust the system "password" field options in the same way as the regular Collection.fields. e.g.:
        collection.fields.getByName("password").min = 10
    `}
/>

<p>
    The Collection create/update operations are also simplified and the <code>Dao</code> and
    <code>CollectionUpsertForm</code> abstractions have been removed.
</p>
<p>
    <code>$app.save(collection)</code> both validate and persist the collection. Use
    <code>$app.saveNoValidate(collection)</code> if you want to skip the validations.
</p>
<p>Below is an example <code>CollectionUpsertForm</code> migration:</p>
<UpgradeTabs
    before={`
        const collection = new Collection()

        const form = new CollectionUpsertForm($app, collection)
        form.name = "example"
        form.type = "base"
        form.listRule = null
        form.viewRule = "@request.auth.id != ''"
        form.createRule = ""
        form.updateRule = "@request.auth.id != ''"
        form.deleteRule = null
        form.schema.addField(new SchemaField({
            name:     "title",
            type:     "text",
            required: true,
            options: {
                max: 10,
            },
        }))
        form.schema.addField(new SchemaField({
            name:     "users",
            type:     "relation",
            options: {
                maxSelect:     5,
                collectionId:  "ae40239d2bc4477",
                cascadeDelete: true,
            },
        }))

        form.submit()
    `}
    after={`
        const collection = new BaseCollection("name")

        collection.listRule = null
        collection.viewRule = "@request.auth.id != ''"
        collection.createRule = ""
        collection.updateRule = "@request.auth.id != ''"
        collection.deleteRule = null
        collection.fields.add(new TextField({
            name:     "title",
            required: true,
            max:      10,
        }))
        collection.fields.add(new RelationField({
            name:          "users",
            maxSelect:     5,
            collectionId:  "ae40239d2bc4477",
            cascadeDelete: true,
        }))

        $app.save(collection)
    `}
/>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Migration changes" />
<div class="alert">
    <div class="content">
        <p>
            If your existing migrations are all autogenerated, you may find it easier to upgrade by deleting
            all of them and run with the PocketBase v0.23.0 executable
            <code>./pocketbase migrate collections</code>
            which will create a full snapshot of your latest collections configuration.
        </p>
        <p>
            Optionally, after that you can also run <code>./pocketbase migrate history-sync</code> to remove the
            deleted migrations from the applied migrations history.
        </p>
    </div>
</div>
<p>
    The <code>migration</code> function accept the transactional app instance as argument instead of
    <code>dbx.Builder</code>. This allow access not only to the database but also to the app settings,
    filesystem, mailer, etc.
</p>
<UpgradeTabs
    before={`
        migrate((db) => {
            const dao = new Dao(db);

            const settings = dao.findSettings()
            settings.meta.appName = "test"
            settings.logs.maxDays = 2

            dao.saveSettings(settings)
        })
    `}
    after={`
        migrate((app) => {
            const settings = app.settings()
            settings.meta.appName = "test"
            settings.logs.maxDays = 2

            app.save(settings)
        })
    `}
/>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Routing changes" />

<p>
    PocketBase v0.23.0 ships with a new router built on top of the standard
    <a href="https://go.dev/blog/routing-enhancements" target="_blank" rel="noopener noreferrer">
        Go 1.22 mux enhancements
    </a>.
    <br />
    Some of the more notable differences are:
</p>
<ul>
    <li>
        Route path parameters must comply with the
        <a href="https://go.dev/blog/routing-enhancements" target="_blank" rel="noopener noreferrer">
            Go 1.22 mux syntax
        </a>.
        <br />
        Or in other words <code>:param</code> must be replaced with <code>{`{param}`}</code>. For static path
        parameter instead of <code>*</code> you have to use special
        <code>{`{path...}`}</code> param.
    </li>
    <li>
        Similar to the new hook handlers, middlewares must call <code>e.next()</code> in order to proceed with
        the execution chain.
    </li>
    <li>
        To access the auth state in a route you can call <code>e.auth</code>. Similarly, to set a new logged
        auth state you can simply assign a new auth record to the <code>e.auth</code> field.
    </li>
    <li>
        Because admins are now <code>_superusers</code> auth collection records, <code>e.auth</code> will be
        set to the authenticated superuser.
        <br />
        To check whether <code>e.auth</code> is a superuser you can use the <code>e.hasSuperuserAuth()</code>
        helper (or alternatively check the record method <code>e.auth.isSuperuser()</code> or
        <code>e.auth.collection().name == "_superusers"</code>).
    </li>
    <li>
        <code>$apis.requestInfo(c)</code> has been replaced with <code>e.requestInfo()</code>.
        <br />
        Note also that the <code>requestInfo.data</code> field was renamed to <code>requestInfo.body</code>
        for consistency with the <code>@request.body.*</code> API rules change.
    </li>
</ul>

<p class="txt-bold">Below you can find a short comparison table with the new routing interface:</p>

<HeadingLink tag="h6" title="Route registration" />
<UpgradeTabs
    before={`
        routerAdd("GET", "/hello/:name", (c) => {
            let name = c.pathParam("name")

            return c.json(200, { "message": "Hello " + name })
        }, $apis.requireRecordAuth())
    `}
    after={`
        routerAdd("GET", "/hello/{name}", (e) => {
            let name = e.request.pathValue("name")

            return e.json(200, { "message": "Hello " + name })
        }, $apis.requireAuth())
    `}
/>

<HeadingLink tag="h6" title="Static files serving" />
<UpgradeTabs
    before={`
        routerAdd("GET", "/*", $apis.staticDirectoryHandler("/path/to/public", false))
    `}
    after={`
        routerAdd("GET", "/{path...}", $apis.static("/path/to/public", false))
    `}
/>

<HeadingLink tag="h6" title="Middleware registration" />
<UpgradeTabs
    before={`
        routerUse((next) => {
            const header = c.request().header.get("Some-Header")
            if (!header) {
                throw new BadRequestError("Invalid request")
            }

            return (c) => {
                return next(c)
            }
        })
    `}
    after={`
        routerUse((e) => {
            const header = e.request.header.get("Some-Header")
            if (!header) {
                throw new BadRequestError("Invalid request")
            }

            return e.next();
        })
    `}
/>

<HeadingLink tag="h6" title="Retrieving the current auth state" />
<UpgradeTabs
    before={`
        // "c" is the echo httpContext

        const admin  = c.get("admin")      // admin model
        const record = c.get("authRecord") // auth record model

        // you can also read the auth state from the cached request info
        const info   = $apis.requestInfo(c)
        const admin  = info.admin
        const record = info.authRecord

        const isAdminAuth = admin != null
    `}
    after={`
        // "e" is the request event

        const auth = e.auth // auth record model

        // you can also read the auth state from the cached request info
        const info = e.requestInfo()
        const auth = info.auth

        const isSuperuserAuth = auth?.isSuperuser() // or e.hasSuperuserAuth()
    `}
/>

<HeadingLink tag="h6" title="Reading path parameters" />
<UpgradeTabs
    before={`
        const id = c.pathParam("id")
    `}
    after={`
        const id = e.request.pathValue("id")
    `}
/>

<HeadingLink tag="h6" title="Reading query parameters" />
<UpgradeTabs
    before={`
        const search = c.queryParam("search")

        // or via the cached request object
        const search = $apis.requestInfo(c).query.search
    `}
    after={`
        const search = e.request.url.query().get("test")

        // or via the cached request object
        const search = e.requestInfo().query.search
    `}
/>

<HeadingLink tag="h6" title="Reading request headers" />
<UpgradeTabs
    before={`
        const token = c.request().header.get("Some-Header")

        // or via the cached request object (the header value is always normalized)
        const token = $apis.requestInfo(c).headers["some_header"]
    `}
    after={`
        const token = e.request.header.get("Some-Header")

        // or via the cached request object (the header value is always normalized)
        const token = e.requestInfo().headers["some_header"]
    `}
/>

<HeadingLink tag="h6" title="Writing response headers" />
<UpgradeTabs
    before={`
        c.response().header().set("Some-Header", "123")
    `}
    after={`
        e.response.header().set("Some-Header", "123")
    `}
/>

<HeadingLink tag="h6" title="Reading request body" />
<UpgradeTabs
    before={`
        // read/scan the request body fields into a typed object
        // (note that the echo request body cannot be read twice with "bind")
        const body = new DynamicModel({
            title: "",
        })
        c.bind(body)
        console.log(body.title)

        // read the body via the cached request object
        const body = $apis.requestInfo(c).data
        console.log(body.title)

        // read single multipart/form-data field
        const title = c.formValue("title")

        // read single multipart/form-data file
        const doc = c.formFile("document")

        // convert the multipart/form-data file into Array<$filesystem.File>
        const doc2 = [$filesystem.fileFromMultipart(doc)]
    `}
    after={`
        // read/scan the request body fields into a typed object
        // (it safe to be read multiple times)
        const body = new DynamicModel({
            title: "",
        })
        e.bindBody(body)
        console.log(body.title)

        // read the body via the cached request object
        const body = e.requestInfo().body
        console.log(body.title)

        // read single multipart/form-data field
        const title = e.request.formValue("title")

        // read single multipart/form-data file
        const doc = e.request.formFile("document")

        // return the uploaded files as Array<$filesystem.File>
        const doc2 = e.findUploadedFiles("document")
    `}
/>

<HeadingLink tag="h6" title="Writing response body" />
<UpgradeTabs
    before={`
        // send response with json body
        c.json(200, {"name": "John"})

        // send response with string body
        c.string(200, "Lorem ipsum...")

        // send response with html body
        // (check also the "Rendering templates" section)
        c.html(200, "<h1>Hello!</h1>")

        // redirect
        c.redirect(307, "https://example.com")

        // send response with no body
        c.noContent(204)
    `}
    after={`
        // send response with json body
        e.json(200, {"name": "John"})

        // send response with string body
        e.string(200, "Lorem ipsum...")

        // send response with html body
        // (check also the "Rendering templates" section)
        e.html(200, "<h1>Hello!</h1>")

        // redirect
        e.redirect(307, "https://example.com")

        // send response with no body
        e.noContent(204)
    `}
/>

<HeadingLink tag="h6" title="Builtin middlewares" />
<UpgradeTabs
    before={`
        $apis.requireRecordAuth([optCollectionNames...])
    `}
    after={`
        $apis.requireAuth([optCollectionNames...])
    `}
/>
<UpgradeTabs
    before={`
        $apis.requireAdminAuth()
    `}
    after={`
        // the same as $apis.requireAuth("_superusers")
        $apis.requireSuperuserAuth()
    `}
/>
<UpgradeTabs
    before={`
        $apis.requireAdminAuthOnlyIfAny($app)
    `}
    after={`
        N/A
    `}
/>
<UpgradeTabs
    before={`
        $apis.requireAdminOrRecordAuth("users")
    `}
    after={`
        $apis.requireAuth("_superusers", "users")
    `}
/>
<UpgradeTabs
    before={`
        $apis.requireAdminOrOwnerAuth(ownerIdParam)
    `}
    after={`
        $apis.requireSuperuserOrOwnerAuth(ownerIdParam)
    `}
/>
<UpgradeTabs
    before={`
        $apis.activityLogger(app)
    `}
    after={`
        // No longer needed because it is registered by default for all routes.
        // If you want to disable the log of successful route execution you can attach the $apis.skipSuccessActivityLog() middleware.
    `}
/>

<HeadingLink tag="h6" title="API helpers" />
<UpgradeTabs
    before={`
        $apis.recordAuthResponse($app, c, record)
    `}
    after={`
        $apis.recordAuthResponse(e, record)
    `}
/>
<UpgradeTabs
    before={`
        $apis.enrichRecord(c, $app.dao(), record, "categories")
        $apis.enrichRecords(c, $app.dao(), records, "categories")
    `}
    after={`
        $apis.enrichRecord(e, record, "categories")
        $apis.enrichRecords(e, records, "categories")
    `}
/>

<!-- ------------------------------------------------------------- -->

<HeadingLink title="Event hooks changes" />

<div class="alert">
    <div class="content">
        <p>
            For more details about all new hooks and their event properties, please refer to the
            <code>on*</code> method docs in the
            <a href="/jsvm/index.html" target="_blank">JSVM reference</a>.
        </p>
    </div>
</div>

<HeadingLink tag="h6" class="txt-mono" title="onBeforeBootstrap -> onBootstrap" />
<UpgradeTabs
    before={`
        onBeforeBootstrap((e) => {
            // ...
        })
    `}
    after={`
        onBootstrap((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAfterBootstrap -> onBootstrap" />
<UpgradeTabs
    before={`
        onAfterBootstrap((e) => {
            // ...
        })
    `}
    after={`
        onBootstrap((e) => {
            e.next()

            // ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onBeforeApiError/onAfterApiError -> any middleware" />
<UpgradeTabs
    before={`
        onBeforeApiError((e) => {
            // ...
        })
    `}
    after={`
        routerUse((e) => {
            try {
                e.next()
            } catch (err) {
                // ...
            }
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onTerminate" />
<UpgradeTabs
    before={`
        onTerminate((e) => {
            // ...
        })
    `}
    after={`
        onTerminate((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelBeforeCreate -> onRecordCreate" />
<UpgradeTabs
    before={`
        onModelBeforeCreate((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelCreate is available if you are targeting non-Record/Collection models
        onRecordCreate((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelAfterCreate -> onRecordAfterCreateSuccess" />
<UpgradeTabs
    before={`
        onModelAfterCreate((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelAfterCreateSuccess is available if you are targeting non-Record/Collection models
        onRecordAfterCreateSuccess((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelBeforeUpdate -> onRecordUpdate" />
<UpgradeTabs
    before={`
        onModelBeforeUpdate((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelUpdate is available if you are targeting non-Record/Collection models
        onRecordUpdate((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelAfterUpdate -> onRecordAfterUpdateSuccess" />
<UpgradeTabs
    before={`
        onModelAfterUpdate((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelAfterUpdateSuccess is available if you are targeting non-Record/Collection models
        onRecordAfterUpdateSuccess((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelBeforeDelete -> onRecordDelete" />
<UpgradeTabs
    before={`
        onModelBeforeDelete((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelDelete is available if you are targeting non-Record/Collection models
        onRecordDelete((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onModelAfterDelete -> onRecordAfterDeleteSuccess" />
<UpgradeTabs
    before={`
        onModelAfterDelete((e) => {
            // e.model ...
        })
    `}
    after={`
        // note: onModelAfterDeleteSuccess is available if you are targeting non-Record/Collection models
        onRecordAfterDeleteSuccess((e) => {
            // e.record ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerBeforeAdminResetPasswordSend -> onMailerRecordPasswordResetSend"
/>
<UpgradeTabs
    before={`
        onMailerBeforeAdminResetPasswordSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordPasswordResetSend((e) => {
            // e.admin -> e.record ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerAfterAdminResetPasswordSend -> onMailerRecordPasswordResetSend"
/>
<UpgradeTabs
    before={`
        onMailerAfterAdminResetPasswordSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordPasswordResetSend((e) => {
            e.next()

            // e.admin -> e.record ...
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerBeforeRecordResetPasswordSend -> onMailerRecordPasswordResetSend"
/>
<UpgradeTabs
    before={`
        onMailerBeforeRecordResetPasswordSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordPasswordResetSend((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerAfterRecordResetPasswordSend -> onMailerRecordPasswordResetSend"
/>
<UpgradeTabs
    before={`
        onMailerAfterRecordResetPasswordSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordPasswordResetSend((e) => {
            e.next()

            // ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerBeforeRecordVerificationSend -> onMailerRecordVerificationSend"
/>
<UpgradeTabs
    before={`
        onMailerBeforeRecordVerificationSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordVerificationSend((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerAfterRecordVerificationSend -> onMailerRecordVerificationSend"
/>
<UpgradeTabs
    before={`
        onMailerAfterRecordVerificationSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordVerificationSend((e) => {
            e.next()

            // ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerBeforeRecordChangeEmailSend -> onMailerRecordEmailChangeSend"
/>
<UpgradeTabs
    before={`
        onMailerBeforeRecordChangeEmailSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordEmailChangeSend((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onMailerAfterRecordChangeEmailSend -> onMailerRecordEmailChangeSend"
/>
<UpgradeTabs
    before={`
        onMailerAfterRecordChangeEmailSend((e) => {
            // ...
        })
    `}
    after={`
        onMailerRecordEmailChangeSend((e) => {
            e.next()

            // ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordsListRequest" />
<p>
    <em>
        Side-note: if you are using this hook simply for adding/removing record fields you may want to check
        <code>onRecordEnrich</code> instead
    </em>
</p>
<UpgradeTabs
    before={`
        onRecordsListRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordsListRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordViewRequest" />
<p>
    <em>
        Side-note: if you are using this hook simply for adding/removing record fields you may want to check
        <code>onRecordEnrich</code> instead
    </em>
</p>
<UpgradeTabs
    before={`
        onRecordViewRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordViewRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordBeforeCreateRequest -> onRecordCreateRequest" />
<p>
    <em>
        With v0.23+ the hook fires <strong>before</strong> the record validations allowing you to adjust "Nonempty"
        fields before checking the constraint.
    </em>
</p>
<UpgradeTabs
    before={`
        onRecordBeforeCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordCreateRequest((e) => {
            // uploaded files are simple values as part of the e.record;
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordAfterCreateRequest -> onRecordCreateRequest" />
<UpgradeTabs
    before={`
        onRecordAfterCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordCreateRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordBeforeUpdateRequest -> onRecordUpdateRequest" />
<p>
    <em>
        With v0.23+ the hook fires <strong>before</strong> the record validations allowing you to adjust "Nonempty"
        fields before checking the constraint.
    </em>
</p>
<UpgradeTabs
    before={`
        onRecordBeforeUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordUpdateRequest((e) => {
            // uploaded files are simple values as part of the e.record;
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordAfterUpdateRequest -> onRecordUpdateRequest" />
<UpgradeTabs
    before={`
        onRecordAfterUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordUpdateRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordBeforeDeleteRequest -> onRecordDeleteRequest" />
<UpgradeTabs
    before={`
        onRecordBeforeDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordAfterDeleteRequest -> onRecordDeleteRequest" />
<UpgradeTabs
    before={`
        onRecordAfterDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordAuthRequest" />
<UpgradeTabs
    before={`
        onRecordAuthRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeAuthWithPasswordRequest -> onRecordAuthWithPasswordRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeAuthWithPasswordRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithPasswordRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterAuthWithPasswordRequest -> onRecordAuthWithPasswordRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterAuthWithPasswordRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithPasswordRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeAuthWithOAuth2Request -> onRecordAuthWithOAuth2Request"
/>
<UpgradeTabs
    before={`
        onRecordBeforeAuthWithOAuth2Request((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithOAuth2Request((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterAuthWithOAuth2Request -> onRecordAuthWithOAuth2Request"
/>
<UpgradeTabs
    before={`
        onRecordAfterAuthWithOAuth2Request((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithOAuth2Request((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeAuthRefreshRequest -> onRecordAuthRefreshRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeAuthRefreshRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRefreshRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterAuthRefreshRequest -> onRecordAuthRefreshRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterAuthRefreshRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRefreshRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRecordListExternalAuthsRequest -> onRecordsListRequest" />
<em>External auths are converted to system <code>_externalAuths</code> collection records.</em>
<UpgradeTabs
    before={`
        onRecordListExternalAuthsRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordsListRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_externalAuths")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeUnlinkExternalAuthRequest -> onRecordDeleteRequest"
/>
<em>External auths are converted to system <code>_externalAuths</code> collection records.</em>
<UpgradeTabs
    before={`
        onRecordBeforeUnlinkExternalAuthRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_externalAuths")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterUnlinkExternalAuthRequest -> onRecordDeleteRequest"
/>
<em>External auths are converted to system <code>_externalAuths</code> collection records.</em>
<UpgradeTabs
    before={`
        onRecordAfterUnlinkExternalAuthRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_externalAuths")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeRequestPasswordResetRequest -> onRecordRequestPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeRequestPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestPasswordResetRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterRequestPasswordResetRequest -> onRecordRequestPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterRequestPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestPasswordResetRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeConfirmPasswordResetRequest -> onRecordConfirmPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeConfirmPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmPasswordResetRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterConfirmPasswordResetRequest -> onRecordConfirmPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterConfirmPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmPasswordResetRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeRequestVerificationRequest -> onRecordRequestVerificationRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeRequestVerificationRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestVerificationRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterRequestVerificationRequest -> onRecordRequestVerificationRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterRequestVerificationRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestVerificationRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeConfirmVerificationRequest -> onRecordConfirmVerificationRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeConfirmVerificationRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmVerificationRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterConfirmVerificationRequest -> onRecordConfirmVerificationRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterConfirmVerificationRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmVerificationRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeRequestEmailChangeRequest -> onRecordRequestEmailChangeRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeRequestEmailChangeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestEmailChangeRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterRequestEmailChangeRequest -> onRecordRequestEmailChangeRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterRequestEmailChangeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestEmailChangeRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordBeforeConfirmEmailChangeRequest -> onRecordConfirmEmailChangeRequest"
/>
<UpgradeTabs
    before={`
        onRecordBeforeConfirmEmailChangeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmEmailChangeRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRecordAfterConfirmEmailChangeRequest -> onRecordConfirmEmailChangeRequest"
/>
<UpgradeTabs
    before={`
        onRecordAfterConfirmEmailChangeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmEmailChangeRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRealtimeConnectRequest" />
<UpgradeTabs
    before={`
        onRealtimeConnectRequest((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeConnectRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRealtimeDisconnectRequest -> onRealtimeConnectRequest" />
<UpgradeTabs
    before={`
        onRealtimeDisconnectRequest((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeConnectRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRealtimeBeforeMessageSend -> onRealtimeMessageSend" />
<UpgradeTabs
    before={`
        onRealtimeBeforeMessageSend((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeMessageSend((e) => {
            // ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onRealtimeAfterMessageSend -> onRealtimeMessageSend" />
<UpgradeTabs
    before={`
        onRealtimeAfterMessageSend((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeMessageSend((e) => {
            e.next()

            // ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRealtimeBeforeSubscribeRequest -> onRealtimeSubscribeRequest"
/>
<UpgradeTabs
    before={`
        onRealtimeBeforeSubscribeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeSubscribeRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onRealtimeAfterSubscribeRequest -> onRealtimeSubscribeRequest"
/>
<UpgradeTabs
    before={`
        onRealtimeAfterSubscribeRequest((e) => {
            // ...
        })
    `}
    after={`
        onRealtimeSubscribeRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onFileDownloadRequest" />
<UpgradeTabs
    before={`
        onFileDownloadRequest((e) => {
            // ...
        })
    `}
    after={`
        onFileDownloadRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onFileBeforeTokenRequest -> onFileTokenRequest" />
<UpgradeTabs
    before={`
        onFileBeforeTokenRequest((e) => {
            // ...
        })
    `}
    after={`
        onFileTokenRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onFileAfterTokenRequest -> onFileTokenRequest" />
<UpgradeTabs
    before={`
        onFileAfterTokenRequest((e) => {
            // ...
        })
    `}
    after={`
        onFileTokenRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionsListRequest" />
<UpgradeTabs
    before={`
        onCollectionsListRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionsListRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionViewRequest" />
<UpgradeTabs
    before={`
        onCollectionViewRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionViewRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionBeforeCreateRequest -> onCollectionCreateRequest" />
<p>
    <em>
        With v0.23+ the hook fires <strong>before</strong> the collection validations.
    </em>
</p>
<UpgradeTabs
    before={`
        onCollectionBeforeCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionCreateRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionAfterCreateRequest -> onCollectionCreateRequest" />
<UpgradeTabs
    before={`
        onCollectionAfterCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionCreateRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionBeforeUpdateRequest -> onCollectionUpdateRequest" />
<p>
    <em>
        With v0.23+ the hook fires <strong>before</strong> the collection validations allowing you to adjust "Nonempty"
        fields before checking the constraint.
    </em>
</p>
<UpgradeTabs
    before={`
        onCollectionBeforeUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionUpdateRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionAfterUpdateRequest -> onCollectionUpdateRequest" />
<UpgradeTabs
    before={`
        onCollectionAfterUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionUpdateRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionBeforeDeleteRequest -> onCollectionDeleteRequest" />
<UpgradeTabs
    before={`
        onCollectionBeforeDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionDeleteRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onCollectionAfterDeleteRequest -> onCollectionDeleteRequest" />
<UpgradeTabs
    before={`
        onCollectionAfterDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionDeleteRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onCollectionsBeforeImportRequest -> onCollectionsImportRequest"
/>
<UpgradeTabs
    before={`
        onCollectionBeforeImportRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionsImportRequest((e) => {
            // "e.collections"  is replaced with "e.collectionsData" which is just a map...

            e.next()
        })
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onCollectionsAfterImportRequest -> onCollectionsImportRequest"
/>
<UpgradeTabs
    before={`
        onCollectionsAfterImportRequest((e) => {
            // ...
        })
    `}
    after={`
        onCollectionsImportRequest((e) => {
            e.next()

            // "e.collections"  is replaced with "e.collectionsData" which is just a map...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onSettingsListRequest" />
<UpgradeTabs
    before={`
        onSettingsListRequest((e) => {
            // ...
        })
    `}
    after={`
        onSettingsListRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onSettingsBeforeUpdateRequest -> onSettingsUpdateRequest" />
<p>
    <em>
        With v0.23+ the hook fires <strong>before</strong> the settings validations.
    </em>
</p>
<UpgradeTabs
    before={`
        onSettingsBeforeUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onSettingsUpdateRequest((e) => {
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onSettingsAfterUpdateRequest -> onSettingsUpdateRequest" />
<UpgradeTabs
    before={`
        onSettingsAfterUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onSettingsUpdateRequest((e) => {
            e.next()

            // "e.httpContext" is no longer available because "e" is the request event itself ...
        })
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminsListRequest -> onRecordsListRequest" />
<UpgradeTabs
    before={`
        onAdminsListRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordsListRequest((e) => {
            // e.admins -> e.records
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminViewRequest -> onRecordViewRequest" />
<UpgradeTabs
    before={`
        onAdminViewRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordViewRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminBeforeCreateRequest -> onRecordCreateRequest" />
<UpgradeTabs
    before={`
        onAdminBeforeCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordCreateRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminAfterCreateRequest -> onRecordCreateRequest" />
<UpgradeTabs
    before={`
        onAdminAfterCreateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordCreateRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminBeforeUpdateRequest -> onRecordUpdateRequest" />
<UpgradeTabs
    before={`
        onAdminBeforeUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordUpdateRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminAfterUpdateRequest -> onRecordUpdateRequest" />
<UpgradeTabs
    before={`
        onAdminAfterUpdateRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordUpdateRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminBeforeDeleteRequest -> onRecordDeleteRequest" />
<UpgradeTabs
    before={`
        onAdminBeforeDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminAfterDeleteRequest -> onRecordDeleteRequest" />
<UpgradeTabs
    before={`
        onAdminAfterDeleteRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordDeleteRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminAuthRequest -> onRecordAuthRequest" />
<UpgradeTabs
    before={`
        onAdminAuthRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminBeforeAuthWithPasswordRequest -> onRecordAuthWithPasswordRequest"
/>
<UpgradeTabs
    before={`
        onAdminBeforeAuthWithPasswordRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithPasswordRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminAfterAuthWithPasswordRequest -> onRecordAuthWithPasswordRequest"
/>
<UpgradeTabs
    before={`
        onAdminAfterAuthWithPasswordRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthWithPasswordRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminBeforeAuthRefreshRequest -> onRecordAuthRefreshRequest"
/>
<UpgradeTabs
    before={`
        onAdminBeforeAuthRefreshRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRefreshRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink tag="h6" class="txt-mono" title="onAdminAfterAuthRefreshRequest -> onRecordAuthRefreshRequest" />
<UpgradeTabs
    before={`
        onAdminAfterAuthRefreshRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordAuthRefreshRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminBeforeRequestPasswordResetRequest -> onRecordRequestPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onAdminBeforeRequestPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestPasswordResetRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminAfterRequestPasswordResetRequest -> onRecordRequestPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onAdminAfterRequestPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordRequestPasswordResetRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminBeforeConfirmPasswordResetRequest -> onRecordConfirmPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onAdminBeforeConfirmPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmPasswordResetRequest((e) => {
            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...

            e.next()
        }, "_superusers")
    `}
/>

<HeadingLink
    tag="h6"
    class="txt-mono"
    title="onAdminAfterConfirmPasswordResetRequest -> onRecordConfirmPasswordResetRequest"
/>
<UpgradeTabs
    before={`
        onAdminAfterConfirmPasswordResetRequest((e) => {
            // ...
        })
    `}
    after={`
        onRecordConfirmPasswordResetRequest((e) => {
            e.next()

            // e.admin -> e.record
            // "e.httpContext" is no longer available because "e" is the request event itself ...
        }, "_superusers")
    `}
/>

<HeadingLink title="Other minor changes" />

<HeadingLink tag="h6" class="txt-mono" title="$http.send()" />
<p>
    <code>$http.send()</code> no longer sends a default <code>Content-Type: application/json</code> header with
    the request.
</p>
<UpgradeTabs
    before={`
        const res = $http.send({
            url: "https://example.com/data.json",
        })
    `}
    after={`
        const res = $http.send({
            url: "https://example.com/data.json",
            headers: { "content-type": "application/json"}
        })
    `}
/>
